import type { BrowserContext, Locator, Page } from 'playwright';
import type { SafetyState } from '../agent/safety.js';

/**
 * A ref entry maps a numbered reference from the observe() tree
 * to a pre-built Playwright Locator. This is the Playwright MCP
 * approach: snapshot → refs → click by ref.
 */
export interface RefEntry {
  ref: number;
  role: string;
  name: string;
  locator: Locator;
}

/**
 * Shared types for the tool layer.
 *
 * We deliberately do NOT hold a fixed Page reference — the user can open
 * tabs, close tabs, or navigate away in the visible Chromium window at any
 * moment. Every tool call resolves the "current active page" dynamically
 * via `getPage()`, which looks at `context.pages()`, prefers the most
 * recently opened non-blank tab, and creates a fresh one if every tab was
 * closed.
 *
 * ToolContext is built once per run by the agent loop and passed to
 * every dispatch() invocation.
 */

export interface ToolContext {
  /** Live browser context — shared across tabs. */
  context: BrowserContext;
  /** Resolve the currently-active page. May create a new one if needed. */
  getPage: () => Promise<Page>;
  /**
   * DOM sub-agent (single-match) — kept as INTERNAL fallback used by
   * the grounded click/type cascade in src/tools/grounded.ts when
   * Playwright's semantic locators (getByRole / getByText /
   * getByPlaceholder / getByLabel) all return zero matches. The
   * agent itself never sees this — it is reachable only through the
   * cascade and never as a first-class tool.
   */
  queryDom?: (query: string) => Promise<string>;
  /** Security layer state — if absent, guards are disabled. */
  safety?: SafetyState;
  /**
   * Set of "role:name" keys (lowercased, normalised whitespace) for
   * the items rendered by the most recent successful observe() call
   * on this run. Populated as a side effect of observe(). Read by the
   * grounded click/type handlers to validate that the agent's
   * `target` was actually present in the perception it just received
   * — this enforces the "no invented locators between observe and
   * click" rule structurally instead of via prompt guidance.
   *
   * Cleared by navigate_to_url (because the new page invalidates the
   * old keys) and refreshed by every observe() call.
   */
  lastObserveVisibleKeys?: Set<string>;
  /** Verbatim text of the last observe() output, for diagnostics. */
  lastObserveText?: string;
  /**
   * Ref → Locator map built by the most recent observe() or mini-tree.
   * click(ref) / type(ref) resolve directly from this map — no cascade.
   */
  refMap?: Map<number, RefEntry>;
  /**
   * Cached ariaSnapshot YAML from the post-mutation observer snapshot.
   * Populated by the loop after every mutating tool. Consumed (and cleared)
   * by the next observe() call if the URL still matches — avoids a redundant
   * ariaSnapshot CDP call (~50-200ms).
   */
  cachedAriaYaml?: { url: string; yaml: string };
}

export interface ToolResult {
  ok: boolean;
  text: string;
  image_base64?: string;
  control?:
    | 'finish'
    | 'ask_user'
    | 'confirm_action'
    | 'respond'
    | 'create_plan'
    | 'verify';
  question?: string;
  summary?: string;
  success?: boolean;
  intent?: string;
  target?: string;
  /** For control="respond": the narrative message the agent wants to show the user. */
  message?: string;
  /** For control="create_plan": the plan payload. */
  plan?: AgentPlan;
  /** For control="verify": the verification payload. */
  verification?: AgentVerification;
}

/**
 * The agent's own plan for the current goal. Generated by create_plan
 * at the start of each turn. Entirely written by the agent in its own
 * words — no templates, no category rules. The loop uses it only as a
 * structural gatekeeper: before finish(success=true) the agent must
 * have called verify at least once with verdict="pass".
 */
export interface AgentPlan {
  /** Single sentence describing the literal observable state that proves the goal. */
  success_condition: string;
  /** Ordered list of sub-goals, agent's own decomposition of the task. */
  subgoals: string[];
  /** How the agent intends to verify success at the end (evidence strategy). */
  verification_strategy: string;
  /** Risks or known traps the agent wants to remember. */
  risks?: string[];
}

/**
 * A verification checkpoint. The agent emits one of these after it
 * believes a sub-goal (or the whole goal) has been achieved, reporting
 * what evidence it has and its honest verdict.
 */
export interface AgentVerification {
  /** Which part of the plan this verification covers (sub-goal text or "goal"). */
  target: string;
  /** What the agent observed on the page that is supposed to prove the target. */
  evidence: string;
  /** Honest self-assessment. */
  verdict: 'pass' | 'fail' | 'partial';
  /** Short notes, especially on "fail" / "partial". */
  notes?: string;
}

/**
 * Standard active-page resolver. Walks context.pages(), discards closed
 * AND zombie pages (ones whose url() throws — happens when the CDP
 * target is gone but isClosed() hasn't been updated yet), prefers the
 * most recent page whose URL is not about:blank. If everything is
 * closed or dead, opens a fresh page. This is what makes the agent
 * resilient to the user opening/closing tabs and to long-lived
 * persistent sessions developing zombie tabs across runs.
 */
function isAlive(p: Page): boolean {
  if (p.isClosed()) return false;
  try {
    // url() throws on pages with a detached CDP target. Cheap probe.
    p.url();
    return true;
  } catch {
    return false;
  }
}

export function makeGetPage(
  context: BrowserContext,
): () => Promise<Page> {
  return async () => {
    const pages = context.pages().filter(isAlive);
    if (pages.length > 0) {
      // Prefer the most-recently-added non-blank tab.
      for (let i = pages.length - 1; i >= 0; i--) {
        const url = pages[i]!.url();
        if (url && url !== 'about:blank' && url !== 'chrome://newtab/') {
          return pages[i]!;
        }
      }
      return pages[pages.length - 1]!;
    }
    return await context.newPage();
  };
}
